services:  
  web:    
    image: subhashdevopslearner/cicd-django-project:latest
    ports:
      - "8000:8000"    
    command: gunicorn --chdir cicdproject cicdproject.wsgi:application --bind 0.0.0.0:8000 --workers 5  
