apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
data:
  SECRET_KEY: ZGphbmdvLWluc2VjdXJlLTFpOUAmeCVsKWglKHZyNWxoKSM3emo0ZHVAdCU2QCt4KDg5QHo2IzJyOWRfdGEqLWlq
  DB_NAME: cG9zdGdyZXM=
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: cG9zdGdyZXM=
  